flickr:
  epochs: 200
  batch_size: 6000

  hparams:
    hidden_units:
    dropout_rates:
    learning_rate:

reddit:
  epochs: 2000
  batch_size: 2000

ppi:
  epochs: 300
  batch_size: 6000

  hparams:
    hidden_units:
    dropout_rates:
    learning_rate:

ppi-large:
  epochs: 300
  batch_size: 6000

  hparams:
    hidden_units:
    dropout_rates:
    learning_rate:

yelp:
  epochs: 300
  batch_size: 6000

  hparams:
    hidden_units:
    dropout_rates:
    learning_rate: